name: UserInfoAPI
version: 1.0.0
main: com.example.userinfoapi.UserInfoAPIPlugin
api-version: '1.20'
description: 提供用户信息的API接口
author: YourName
website: https://example.com

commands:
  userinfo:
    description: 用户信息API管理命令
    usage: /userinfo <reload|status>
    permission: userinfoapi.admin

permissions:
  userinfoapi.admin:
    description: 管理用户信息API的权限
    default: op